security:
  basic:
    enabled: true
  user:
    name: root
    password: 123456
server:
  port: 8761
eureka:
  #eureka server本身也是一个client
  client:
    register-with-eureka: false    #是否注册到别的eureka
    fetch-registry: false       #是否合并别的eureka的数据
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka